### ISSUE TITLE
应该有一个设置时间的变量定义出来吧 不能根据图片多少 就多少时间啊

### ISSUE THREAD

**Issue by Charlotte3240** [DingHub/RPRingedPages#1]
应该有一个设置时间的变量定义出来吧 不能根据图片多少 就多少时间啊

**Comment by zrcoder** [comment]
实际上RPRingedPages有一个只读属性
@property (nonatomic, strong, readonly) RPPagesCarousel *carousel;
可以通过这个属性设置自动切换时间：（假设你的RPRingedPages实例为pages）
pages.carousel.autoScrollInterval = 5;
